[project]

site_name = "Dessert's Guidebook"
site_description = "A comprehensive, self-learning based book for the game Brickadia"
site_author = "DessertSource"
site_url = "https://dessertsource.github.io/dessert-brickadia-guide"

repo_url = "https://codeberg.org/DessertSource/dessert-brickadia-guide"
repo_name = "dessert-brickadia-guide"

copyright = """
<a href="https://dessertsource.github.io/dessert-brickadia-guide/about/license.html">
&copy; 2026 DessertSource & contribs.</a>
|
<a href="https://dessertsource.github.io/dessert-brickadia-guide/about/privacy-policy.html">
Privacy Policy</a>
"""

watch = [
    "macros.py",
    "docs/assets/javascripts/",
    "docs/assets/stylesheets/"
]

nav = [

    { "Home" = "index.md" },

    { "About" = [
        "about/index.md",
        "about/repository.md",
        "about/issues.md",
        "about/contribution.md",
        "about/license.md",
        "about/privacy-policy.md"
    ]},

    { "Essentials" = [
        "essentials/looking-around.md",
        "essentials/movement.md",
        { "Chat" = [
            "essentials/chat/index.md",
            "essentials/chat/chat-formatting.md",
            "essentials/chat/chat-commands.md",
        ]},
        "essentials/emotes.md",
        "essentials/camera-tools.md",
        "essentials/avatar-editor.md",
        "essentials/palette-editor.md",
    ]},

    { "Wires" = [
        { "Basics" = [
            "wires/basics/what-are-wires.md",
            # "wires/basics/what-are-gates.md",
            # "wires/basics/rerouters",   
            "wires/basics/execution-signals.md",
            "wires/basics/wire-colors.md"
        ]}
    ]}
]

extra_css = [
    "assets/stylesheets/extra.css",
]

extra_javascript = [
    "assets/libraries/glightbox.min.js",
    "assets/libraries/mermaid.min.js",
    "assets/libraries/tex-mml-chtml.js",
    "assets/libraries/tablesort.min.js",
    "assets/libraries/plyr.polyfilled.min.js",
    "assets/javascripts/mermaid.js",
    "assets/javascripts/mathjax.js",
    "assets/javascripts/tablesort.js",
    "assets/javascripts/plyr.js"
]

[project.extra.tags]

Meta = "meta"

Essentials = "estl"
Presets = "prst"
Chat = "chat"
Social = "soci"
Movement = "mvmt"
Camera = "camr"
Filming = "film"
Avatars = "avtr"
Palettes = "palt"
Lighting = "lgng"
Formatting = "fmrt"

Components = "cmpo"

Wires = "wire"
"Wire Variables" = "wvar"

Commands = "cmds"

[project.theme.icon.tag]

meta = "lucide/info"

estl = "lucide/star"
prst = "lucide/notepad-text"
chat = "lucide/message-circle-more"
soci = "lucide/message-circle-heart"
mvmt = "lucide/gamepad-directional"
camr = "lucide/camera"
film = "lucide/clapperboard"
avtr = "lucide/shirt"
palt = "lucide/swatch-book"
lgng = "lucide/spotlight"
fmrt = "lucide/type-outline"

cmpo = "lucide/card-sim"

wire = "lucide/cable"
wvar = "lucide/variable"

cmds = "lucide/square-terminal"

[project.theme]

variant = "modern"

logo = "assets/stylesheets/elements/logo.svg"
favicon = "assets/stylesheets/elements/favicon.svg"
icon.repo = "simple/codeberg"

custom_dir = "docs/assets/overrides"

language = "en"

features = [

    "content.code.annotate",
    "content.code.copy",
    "content.code.select",
    "content.tabs.link",
    "content.footnote.tooltips",
    "content.tooltips",

    "navigation.expand",
    "navigation.footer",
    "navigation.indexes",
    "navigation.path",
    "navigation.tabs",
    "navigation.top",
    "navigation.tracking",

    "toc.follow",

    "search.highlight"

]

[project.plugins.offline]
enabled = true

[[project.theme.palette]]
media = "(prefers-color-scheme)"
toggle.icon = "lucide/sun-moon"
toggle.name = "Switch to light mode"
primary = "indigo"
accent = "indigo"

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"
primary = "indigo"
accent = "indigo"

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to system preference"
primary = "indigo"
accent = "indigo"

[project.theme.font]
text = false
code = false

[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/DessertSource/dessert-brickadia-guide"
name = "View the repository for this guide on GitHub"

[[project.extra.social]]
icon = "simple/codeberg"
link = "https://codeberg.org/DessertSource/dessert-brickadia-guide"
name = "View the repository for this guide on Codeberg"

[[project.extra.polyfills]]
iframe_worker = ""

[project.markdown_extensions.abbr]
[project.markdown_extensions.admonition]
[project.markdown_extensions.attr_list]
[project.markdown_extensions.footnotes]
[project.markdown_extensions.md_in_html]
[project.markdown_extensions.toc]
title = "On this page"
permalink = "¶"
permalink_title = "Anchor link to this section for copying"
[project.markdown_extensions.toc.slugify]
function = "pymdownx.slugs.slugify"
kwds = {case = "lower"}
[project.markdown_extensions.tables]
[project.markdown_extensions.pymdownx.arithmatex]
generic = true
[project.markdown_extensions.pymdownx.blocks.caption]
[project.markdown_extensions.pymdownx.caret]
[project.markdown_extensions.pymdownx.tilde]
[project.markdown_extensions.pymdownx.details]
[project.markdown_extensions.pymdownx.emoji]
emoji_index = "zensical.extensions.emoji.twemoji" 
emoji_generator = "zensical.extensions.emoji.to_svg"
options.custom_icons = ["overrides/.icons"]
[project.markdown_extensions.pymdownx.highlight]
anchor_linenums = true
line_spans = "__span"
pygments_lang_class = true
[project.markdown_extensions.pymdownx.inlinehilite]
[project.markdown_extensions.pymdownx.keys]
key_map = { "asterisk" = "*", "scrollwheel" = "Mouse Scroll Wheel", "leftbutton" = "Left Mouse Button", "middlebutton" = "Middle Mouse Button", "rightbutton" = "Right Mouse Button"}
[project.markdown_extensions.pymdownx.snippets]
auto_append = ["docs/snippets/abbreviations.md"]
check_paths = true
[project.markdown_extensions.pymdownx.superfences]
custom_fences = [
  {name = "mermaid", class = "mermaid", format = "pymdownx.superfences.fence_code_format"}
]
[project.markdown_extensions.pymdownx.smartsymbols]
fractions = false
[project.markdown_extensions.pymdownx.tabbed]
alternate_style = true
[project.markdown_extensions.pymdownx.tabbed.slugify]
object = "pymdownx.slugs.slugify"
kwds = {case = "lower"}
[project.markdown_extensions.pymdownx.tasklist]
custom_checkbox = true
[project.markdown_extensions.zensical.extensions.glightbox]
auto_caption = true
[project.markdown_extensions.zensical.extensions.macros]
module_name = "macros"