site_name: Dessert's Brickadia Guide
site_url: https://dessertsource.github.io/dessert-brickadia-guide
site_author: DessertSource
site_description: >-
  A manual for Brickadia by DessertSource

repo_url: https://github.com/dessertsource/dessert-brickadia-guide
repo_name: dessert-brickadia-guide

copyright: >
  Copyright &copy; 2025 DessertSource –
  <a href="#__consent">Change cookie settings</a>

theme:

  name: material
  logo: assets/logo.svg
  favicon: assets/favicon.svg

  font:
    text: Inter

  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.suggest
    - navigation.footer
    - toc.follow
    - content.tooltips

  icon:
    repo: fontawesome/brands/github
    annotation: material/plus-circle-outline
  
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/theme-light-dark
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: grey
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: black
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to system preference
    
  custom_dir: docs/assets/overrides

extra_css:
  - assets/stylesheets/extra.css

extra_javascript:
  - assets/javascripts/mathjax.js
  - https://unpkg.com/mathjax@4/tex-mml-chtml.js
  - assets/javascripts/tablesort.js
  - https://unpkg.com/tablesort@5.6.0/dist/tablesort.min.js

plugins:

  - search
  - social:
      cards_layout_options:
        font_family: Inter
  - privacy:
      enabled: !ENV [CI, false]
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
  - panzoom
  - glightbox:
      touchNavigation: true
      loop: true
      effect: none
      slide_effect: none
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      auto_themed: true
      auto_caption: true
      caption_position: bottom
      background: gray
      shadow: true
      manual: false
  - print-site:
      add_to_navigation: false
      print_page_title: 'Print Site'
      print_page_basename: 'print_page'
      add_print_site_banner: true
      # Table of contents
      add_table_of_contents: False
      # Content-related
      add_full_urls: false
      enumerate_headings: false
      enumerate_figures: false
      add_cover_page: true
      cover_page_template: ""
      path_to_pdf: ""
      include_css: true
      enabled: true

markdown_extensions:

  - abbr
  - admonition
  - toc:
      permalink: true
      title: On this page
      toc_depth: 0-3
  - attr_list
  - def_list
  - md_in_html
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - assets/icons
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - tables
  - pymdownx.keys
  - pymdownx.snippets
  - footnotes
  - pymdownx.arithmatex:
      generic: true

extra:

  consent:
    title: Cookie Consent
    description: >- 
      There's a Github cookie in here that doesn't
      affect the experience when disabled / rejected.
      I didn't make this pop-up, but I'd rather not have
      GDPR knocking down my door for a documentation website.
    actions:
      - accept
      - reject
      - manage 

  scope: /brickadia-guide/